import { Roboto } from "next/font/google";
import "./globals.css";
import Parent from "./_components/Parent";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <Parent>{children}</Parent>
      </body>
    </html>
  );
}
